indent = 2
margin = 92
always_for_in = true
remove_extra_newlines = true
pipe_to_function_call = true
format_docstrings = true
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
